version: "3.8"
services:
  # Container: redis
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
  # Container: discord bot
  bot:
    container_name: reservoir-discord-bot
    build: .
    depends_on:
      - redis
    command: ["node", "./dist/index.js"]
    env_file:
      - .env
